export default function VeterinaryDisclaimer() {
  return (
    <div className="min-h-screen bg-slate-50 pt-28 pb-20 px-4 sm:px-6 font-sans">
      <div className="max-w-4xl mx-auto space-y-8 text-left">
        {/* Header Title */}
        <div className="space-y-3 border-b border-slate-200 pb-6">
          <h1 className="text-3xl sm:text-4xl font-bold text-slate-900 tracking-tight">
            Veterinary Disclaimer
          </h1>
          <p className="text-xs sm:text-sm text-slate-500 font-medium">
            Important Guidance for Farmers, Livestock Owners & Veterinarians | Chimertech Private Limited
          </p>
        </div>

        {/* Content Section */}
        <div className="bg-white rounded-2xl p-6 sm:p-10 border border-slate-200 shadow-sm space-y-8 text-slate-700 text-sm leading-relaxed font-normal">
          
          {/* AI-Based Assessment */}
          <section className="space-y-3">
            <h2 className="text-lg font-bold text-slate-900">
              1. AI-Based Assessment
            </h2>
            <blockquote className="p-4 rounded-xl bg-slate-50 border-l-4 border-slate-700 text-xs sm:text-sm font-semibold text-slate-900 leading-relaxed">
              "The Body Condition Score generated by this application is based on artificial intelligence analysis of uploaded images. It is intended only as a preliminary assessment and decision-support tool."
            </blockquote>
          </section>

          {/* No Veterinary Diagnosis */}
          <section className="space-y-3">
            <h2 className="text-lg font-bold text-slate-900">
              2. No Veterinary Diagnosis
            </h2>
            <p>
              The application assists farmers and veterinarians but does not replace veterinary expertise. The application does not:
            </p>
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 text-xs text-slate-800 font-medium">
              <div className="p-4 rounded-xl bg-slate-50 border border-slate-200 text-center">Diagnose Diseases</div>
              <div className="p-4 rounded-xl bg-slate-50 border border-slate-200 text-center">Prescribe Medicines</div>
              <div className="p-4 rounded-xl bg-slate-50 border border-slate-200 text-center">Replace Veterinary Examination</div>
            </div>
          </section>

          {/* Veterinary Consultation */}
          <section className="space-y-3">
            <h2 className="text-lg font-bold text-slate-900">
              3. Veterinary Consultation
            </h2>
            <p>Users should consult veterinarians for:</p>
            <ul className="list-disc pl-5 space-y-2 text-slate-600 font-normal">
              <li>Disease confirmation</li>
              <li>Treatment decisions</li>
              <li>Medication management</li>
              <li>Emergency health conditions</li>
            </ul>
          </section>

          {/* AI Accuracy Limitation */}
          <section className="space-y-4">
            <h2 className="text-lg font-bold text-slate-900">
              4. AI Accuracy Limitation
            </h2>
            <p>The result may vary due to environmental and capture factors:</p>
            
            <div className="grid grid-cols-2 sm:grid-cols-3 gap-3 text-xs text-slate-700 font-medium">
              <div className="p-3 rounded-lg bg-slate-50 border border-slate-200">Image quality</div>
              <div className="p-3 rounded-lg bg-slate-50 border border-slate-200">Camera angle</div>
              <div className="p-3 rounded-lg bg-slate-50 border border-slate-200">Lighting conditions</div>
              <div className="p-3 rounded-lg bg-slate-50 border border-slate-200">Animal posture</div>
              <div className="p-3 rounded-lg bg-slate-50 border border-slate-200">Breed variation</div>
              <div className="p-3 rounded-lg bg-slate-50 border border-slate-200">Environmental factors</div>
            </div>
          </section>

          {/* Example Section */}
          <section className="space-y-4">
            <h2 className="text-lg font-bold text-slate-900">
              5. Example Interpretation
            </h2>
            
            <div className="p-6 rounded-2xl bg-slate-900 text-white space-y-4 shadow-md">
              <div className="border-b border-slate-800 pb-3">
                <span className="text-xs font-semibold uppercase text-slate-400">AI Output</span>
                <p className="text-xl font-bold text-white mt-1">Estimated BCS: 3.25</p>
              </div>
              
              <div className="space-y-1">
                <span className="text-xs font-semibold uppercase text-slate-400">Meaning</span>
                <p className="text-xs sm:text-sm font-normal text-slate-200 leading-relaxed">
                  "The result indicates an estimated body condition based on visual analysis. A veterinarian or trained livestock professional should confirm the condition before making management decisions."
                </p>
              </div>
            </div>
          </section>
        </div>
      </div>
    </div>
  );
}
