import React from 'react';

interface AIDisclaimerFooterProps {
  className?: string;
  compact?: boolean;
}

export default function AIDisclaimerFooter({ className = '', compact = false }: AIDisclaimerFooterProps) {
  if (compact) {
    return (
      <div className={`pt-3 border-t border-slate-200/80 text-center flex flex-col items-center justify-center gap-1 ${className}`}>
        <div className="flex items-center gap-1.5">
          <span className="w-1.5 h-1.5 rounded-full bg-emerald-500 animate-pulse flex-shrink-0" />
          <p className="text-[11px] font-black text-slate-700">
            This report and data generated by <span className="text-emerald-600">PashuX AI</span>
          </p>
        </div>
        <p className="text-[9px] font-bold text-slate-400 uppercase tracking-wider">
          Powered by Chimertech Private Limited
        </p>
      </div>
    );
  }

  return (
    <div className={`mt-8 pt-5 border-t border-slate-200/80 text-center flex flex-col items-center justify-center gap-1.5 ${className}`}>
      <div className="inline-flex items-center gap-2 bg-emerald-50/80 border border-emerald-200/80 px-3.5 py-1.5 rounded-full shadow-sm">
        <div className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse flex-shrink-0" />
        <p className="text-xs font-black text-slate-800 tracking-wide">
          This report and data generated by <span className="text-emerald-600 font-black">PashuX AI</span>
        </p>
      </div>
      <p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">
        Powered by Chimertech Private Limited • Official AI Diagnostic Record
      </p>
    </div>
  );
}
