interface Props {
  type?: 'vet' | 'ai' | 'general';
}

const CONFIGS = {
  ai: {
    icon: '⚠️',
    title: 'AI-Assisted Screening Only',
    body: 'This result is generated by an AI vision model analysing visible cattle characteristics from video footage. It is not a confirmed veterinary diagnosis. Always consult a qualified veterinarian before making treatment decisions.',
    color: 'border-amber-500/20 bg-amber-500/[0.04]',
    textColor: 'text-amber-400',
  },
  vet: {
    icon: '🩺',
    title: 'Veterinary Consultation Recommended',
    body: 'Possible visible condition detected. This is an AI-assisted screening result and should be confirmed by a qualified veterinarian. Do not administer medication without professional guidance.',
    color: 'border-red-500/20 bg-red-500/[0.04]',
    textColor: 'text-red-400',
  },
  general: {
    icon: '💡',
    title: 'Important Notice',
    body: 'Chimertech AI tools are designed to assist — not replace — professional veterinary care. Results depend on video quality and visible cattle characteristics.',
    color: 'border-white/[0.08] bg-white/[0.02]',
    textColor: 'text-grey-400',
  },
};

export default function Disclaimer({ type = 'ai' }: Props) {
  const cfg = CONFIGS[type];
  return (
    <div className={`rounded-xl p-4 border ${cfg.color} flex items-start gap-3`}>
      <span className="text-lg flex-shrink-0 mt-0.5">{cfg.icon}</span>
      <div>
        <p className={`text-xs font-semibold ${cfg.textColor} mb-1`}>{cfg.title}</p>
        <p className="text-xs text-grey-500 leading-relaxed">{cfg.body}</p>
      </div>
    </div>
  );
}
