interface Props {
  type?: 'vet' | 'ai' | 'general';
}

export default function Disclaimer({ type = 'ai' }: Props) {
  if (type === 'vet') {
    return (
      <div className="rounded-2xl p-4 border border-rose-200 bg-rose-50/80 flex items-start gap-3 shadow-sm">
        <div className="w-8 h-8 rounded-xl bg-rose-100 text-rose-700 flex items-center justify-center flex-shrink-0 mt-0.5 font-bold">
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2} className="w-5 h-5">
            <path strokeLinecap="round" strokeLinejoin="round" d="M12 9v3.75m9-.75a9 9 0 11-18 0 9 9 0 0118 0zm-9 3.75h.008v.008H12v-.008z" />
          </svg>
        </div>
        <div>
          <p className="text-xs font-black text-rose-900 mb-1">Veterinary Consultation Recommended</p>
          <p className="text-xs text-slate-800 leading-relaxed font-semibold">
            Possible visible condition detected. This is an AI-assisted screening result and should be confirmed by a qualified veterinarian. Do not administer medication without professional guidance.
          </p>
        </div>
      </div>
    );
  }

  if (type === 'general') {
    return (
      <div className="rounded-2xl p-4 border border-emerald-200 bg-emerald-50/80 flex items-start gap-3 shadow-sm">
        <div className="w-8 h-8 rounded-xl bg-emerald-100 text-emerald-800 flex items-center justify-center flex-shrink-0 mt-0.5 font-bold">
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2} className="w-5 h-5">
            <path strokeLinecap="round" strokeLinejoin="round" d="M11.25 11.25l.041-.02a.75.75 0 011.063.852l-.708 2.836a.75.75 0 001.063.853l.041-.021M21 12a9 9 0 11-18 0 9 9 0 0118 0zm-9-3.75h.008v.008H12V8.25z" />
          </svg>
        </div>
        <div>
          <p className="text-xs font-black text-emerald-900 mb-1">Important System Notice</p>
          <p className="text-xs text-slate-800 leading-relaxed font-semibold">
            Chimertech AI tools are designed to assist — not replace — professional veterinary care. Results depend on video clarity and visible cattle characteristics.
          </p>
        </div>
      </div>
    );
  }

  return (
    <div className="rounded-2xl p-4 border border-amber-200 bg-amber-50/80 flex items-start gap-3 shadow-sm">
      <div className="w-8 h-8 rounded-xl bg-amber-100 text-amber-800 flex items-center justify-center flex-shrink-0 mt-0.5 font-bold">
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2} className="w-5 h-5">
          <path strokeLinecap="round" strokeLinejoin="round" d="M12 9v3.75m-9.303 3.376c-.866 1.5.217 3.374 1.948 3.374h14.71c1.73 0 2.813-1.874 1.948-3.374L13.949 3.378c-.866-1.5-3.032-1.5-3.898 0L2.697 16.126zM12 15.75h.008v.008H12v-.008z" />
        </svg>
      </div>
      <div>
        <p className="text-xs font-black text-amber-950 mb-1">AI-Assisted Screening Only</p>
        <p className="text-xs text-slate-800 leading-relaxed font-semibold">
          This result is generated by an AI vision model analysing visible cattle characteristics. It is not a confirmed veterinary diagnosis. Always consult a qualified veterinarian.
        </p>
      </div>
    </div>
  );
}
